name: Build iOS App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install cocoapods
        if [ -f "Podfile" ]; then
          pod install || pod install --repo-update || echo "Pod install failed, continuing with empty Pods"
        fi

    - name: List files in directory
      run: ls -la

    - name: Create exportOptions.plist
      run: |
        cat > exportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>compileBitcode</key>
            <false/>
            <key>signingStyle</key>
            <string>manual</string>
        </dict>
        </plist>
        EOF

    - name: Build iOS App for Distribution
      run: |
        mkdir -p build/logs
        set -o pipefail && xcodebuild clean archive -project VideoWaniOS.xcodeproj -scheme VideoWaniOS -sdk iphoneos -configuration Release -archivePath build/VideoWaniOS.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED=NO | tee build/logs/build.log || exit 1

    - name: Export IPA
      run: |
        # Try standard export first
        xcodebuild -exportArchive -archivePath build/VideoWaniOS.xcarchive -exportPath build/export -exportOptionsPlist exportOptions.plist || true
        
        # If that fails, use manual method as fallback
        if [ ! -f "build/export/VideoWaniOS.ipa" ]; then
          echo "Standard export failed, using manual method..."
          mkdir -p build/Payload
          cp -r build/VideoWaniOS.xcarchive/Products/Applications/VideoWaniOS.app build/Payload/
          cd build && zip -r VideoWaniOS.ipa Payload
          cd ..
        else
          cp build/export/VideoWaniOS.ipa build/VideoWaniOS.ipa
        fi

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: VideoWaniOS
        path: build/VideoWaniOS.ipa

    - name: Archive Build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/

    - name: Upload Build Logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: build/logs/

    - name: Prepare Web Version for Deployment
      run: |
        mkdir -p build/web_version
        if [ -d "web_version" ]; then
          cp -r web_version/* build/web_version/ || true
        fi

    - name: Update manifest.plist with correct URL
      run: |
        sed -i.bak "s|https://Flickinny11.github.io|https://${{ github.repository_owner }}.github.io|g" manifest.plist
        cp manifest.plist build/
        cp index.html build/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
