name: Build iOS App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install CocoaPods dependencies
      run: pod install

    - name: Build iOS App without code signing
      run: |
        xcodebuild clean -project VideoWaniOS.xcodeproj -scheme VideoWaniOS -configuration Release
        xcodebuild -project VideoWaniOS.xcodeproj -scheme VideoWaniOS -configuration Release -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED=NO

    - name: Create IPA Package
      run: |
        mkdir -p build/Payload
        cp -r build/Release-iphoneos/VideoWaniOS.app build/Payload/
        cd build && zip -r VideoWaniOS.ipa Payload

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: VideoWaniOS
        path: build/VideoWaniOS.ipa

    - name: Archive Build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/

    - name: Upload Build Logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: build/logs/
