name: Build iOS App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: Cache Ruby gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install Fastlane
      run: gem install fastlane

    - name: Install CocoaPods
      run: sudo gem install cocoapods
      continue-on-error: true

    - name: Build iOS App without code signing
      run: |
        xcodebuild clean -project VideoWaniOS.xcodeproj -scheme VideoWaniOS -configuration Release -allowProvisioningUpdates
        xcodebuild -project VideoWaniOS.xcodeproj -scheme VideoWaniOS -configuration Release -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED=NO -allowProvisioningUpdates

    - name: Create IPA Package
      run: |
        mkdir -p build/Payload
        cp -r build/Release-iphoneos/VideoWaniOS.app build/Payload/
        cd build && zip -r VideoWaniOS.ipa Payload

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: VideoWaniOS
        path: build/VideoWaniOS.ipa

    - name: Archive Build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/
