name: Build iOS App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install cocoapods
        pod install || true

    - name: List files in directory
      run: ls -la

    - name: Build iOS App for Distribution
      run: |
        mkdir -p build/logs
        xcodebuild clean archive -project VideoWaniOS.xcodeproj -scheme VideoWaniOS -sdk iphoneos -configuration Release -archivePath build/VideoWaniOS.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED=NO | tee build/logs/build.log

    - name: Export IPA
      run: |
        mkdir -p build/Payload
        cp -r build/VideoWaniOS.xcarchive/Products/Applications/VideoWaniOS.app build/Payload/
        cd build && zip -r VideoWaniOS.ipa Payload

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: VideoWaniOS
        path: build/VideoWaniOS.ipa

    - name: Archive Build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/

    - name: Upload Build Logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: build/logs/

    - name: Generate Web Version
      run: |
        mkdir -p build/web_version
        cp -r web_version/* build/web_version/ || true

    - name: Update manifest.plist with correct URL
      run: |
        sed -i '' "s|https://Flickinny11.github.io|https://${{ github.repository_owner }}.github.io|g" manifest.plist
        cp manifest.plist build/
        cp index.html build/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
